### ISSUE TITLE
Database migration fails for updating to any version from Docker Hub.

### ISSUE THREAD

**Issue by Empty2k12** [usefathom/fathom#185]
I just tried updating fathom to the latest version, from the version that added multi site tracking. However, with every version the database migration fails, or does not even run (on version v1.2.0).

```
fathom_1  | time="2018-11-19T11:51:33Z" level=error msg="Error applying database migrations: Unable
to create migration plan because of 12_create_hostnames_table.sql: unknown migration in database"
```

<details><summary>My Docker Compose</summary>
<p>
```

version: "3"

networks:
  proxy:
    external: true
  internal:
    external: false

services:
  fathom:
    image: usefathom/fathom:version-1.2.0
    labels:
      - traefik.backend=fathom
      - traefik.frontend.rule=Host:traffic.infra.my.domain
      - traefik.docker.network=proxy
      - traefik.port=8080
    networks:
      - internal
      - proxy
    volumes:
      - ./fathom.db/fathom.db:/app/fathom.db/
```

</p>
</details>

How do I migrate to a version with working migration that preserves my data?
