### ISSUE TITLE
Config question: Using Docker and SQLite

### ISSUE THREAD

**Issue by pascalandy** [usefathom/fathom#233]
Hello folks!

I'm so glad to have found this project! Can't wait to launch it :)
Some questions about the configuration over compose.

### 1)

As I don't want to use MySQL, I'm looking to set up my compose file with SQLite.
Do I need to remove or add parameters?

```
version: "3"
services:
  fathom:
    image: usefathom/fathom:latest
    ports:
      - "8080:8080"
    environment:
      - "FATHOM_SERVER_ADDR=:8080"
      - "FATHOM_GZIP=true"
      - "FATHOM_DEBUG=false"
      - "FATHOM_DATABASE_DRIVER=sqlite"
      - "FATHOM_DATABASE_NAME=fathom"
      - "FATHOM_DATABASE_USER=fathom"
      - "FATHOM_DATABASE_PASSWORD=ChangeMeASAP"
      - "FATHOM_SECRET=TWEn6GXQDx45PZfmJWvyGpXf5M8b94bszgw8JcJWEd6WxgrnUkLatS34GwjPTvZb"
    restart: always
```

2) Stateful

I don't use docker volumes. I prefer to mount/bind everything.

A) Where is this .db file in the container?
B) Is there other(s) config I should keep (I don't think so from the docker-compose I see in this project).

Many cheers!
Pascal
