### ISSUE TITLE
Fathom cant find Database on same docker network

### ISSUE THREAD

**Issue by b-m-f** [usefathom/fathom#239]
I am running fathom with the following **compose** file:
```
version: "3"
networks:
  fathom:
    external: false
  web:
    external: true
services:
  fathom:
    image: usefathom/fathom:latest
    environment:
      - "FATHOM_SERVER_ADDR=:8080"
      - "FATHOM_GZIP=true"
      - "FATHOM_DEBUG=false"
      - "FATHOM_DATABASE_DRIVER=mysql"
      - "FATHOM_DATABASE_NAME=fathom"
      - "FATHOM_DATABASE_USER=fathom"
      - "FATHOM_DATABASE_PASSWORD=asd"
      - "FATHOM_DATABASE_HOST=fathomdb:3306"
      - "FATHOM_SECRET=asd"
    depends_on:
      - mysql
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.basic.port=8080"
      - "traefik.basic.frontend.rule=Host:asd.asd.asd"
      - "traefik.basic.protocol=http"
    container_name: fathom
    restart: always
    networks:
      - fathom
      - web
  mysql:
    image: mysql:8
    restart: always
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      - "MYSQL_ALLOW_EMPTY_PASSWORD=false"
      - "MYSQL_DATABASE=asd"
      - "MYSQL_PASSWORD=asd"
      - "MYSQL_ROOT_PASSWORD=asd"
      - "MYSQL_USER=asd"
    networks:
      - fathom
    container_name: fathomdb

```

Unfortunately fathom crashes with `Error connecting to database: fathomdb host not found`. 
This happens in https://github.com/usefathom/fathom/blob/master/pkg/datastore/sqlstore/sqlstore.go#L41 .

## Quickfix
Changing `"FATHOM_DATABASE_HOST=fathomdb:3306"` to `"FATHOM_DATABASE_HOST=IP_ADDRESS_OF_DATABASE_CONTAINER:3306"` works just fine. 

## Conclusion
This leads me to believe that this has to do with the DNS resolving. After starting the container and attaching to it with `docker exec -ti fathom bash` and then running `ping -c 4 fathomdb` it works fine,
which should mean that the problem lies in the program, not the container.

I have stumbled upon https://github.com/golang/go/issues/22846 . Could this be related? Even though no details are actually saved in that file and 

`/etc/resolv.conf` contains:
```
nameserver 127.0.0.11
```
