### ISSUE TITLE
Error Reading configuration

### ISSUE THREAD

**Issue by Th3Whit3Wolf** [usefathom/fathom#285]
I am using docker-compose and traefik to run fathom.

my docker-compose.yml

```yml
version: '3'

networks:
  web:
    external: true

services:
  fathom:
    restart: always
    image: usefathom/fathom:latest
    ports:
      - "8080:8080"
    environment:
      - "FATHOM_SERVER_ADDR=:8080"
      - "FATHOM_GZIP=true"
      - "FATHOM_DEBUG=false" 
      - "FATHOM_DATABASE_DRIVER=postgres"
      - "FATHOM_DATABASE_URL=postgresql://postrgress-user:postgress-passwd@db.ondigitalocean.com:25060/fathom?sslmode=require"
      - "FATHOM_SECRET=a-secret-key"
    networks:
      - web
    container_name: fathom
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:fathom.my_domain.com,www.fathom.my_domain.com"
      - "traefik.port=8080"
      - "traefik.backend=fathom-analytics"
```

when I run `docker-compose up` I get this...
```sh
Starting fathom ... done
Attaching to fathom
fathom    | time="2019-08-17T23:58:12Z" level=info msg="Fathom version 1.2.1+43-gb278944, commit b27894431395fed2053b2c9b92340a4a73b05319, built at "
fathom    | time="2019-08-17T23:58:12Z" level=warning msg="Error reading configuration. File `.env` does not exist."
fathom    | time="2019-08-17T23:58:12Z" level=info msg="Connected to postgres database: fathom.db"
```

which is weird be cause I do have a `.env` file

```yaml
FATHOM_SERVER_ADDR=8080
FATHOM_GZIP=true
FATHOM_DEBUG=false
FATHOM_DATABASE_DRIVER=postgres
FATHOM_DATABASE_URL=postgresql://postrgress-user:postgress-passwd@db.ondigitalocean.com:25060/fathom?sslmode=require
FATHOM_SECRET=a-secret-key
```

So I ran `docker-compose up -d` and after it finished I ran `docker exec fathom ./fathom --config=/home/doc/fathom/.env server`

and I got this...
```sh
time="2019-08-18T00:02:42Z" level=info msg="Fathom version 1.2.1+43-gb278944, commit b27894431395fed2053b2c9b92340a4a73b05319, built at "
time="2019-08-18T00:02:42Z" level=warning msg="Error reading configuration. File `/home/doc/fathom/.env` does not exist."
time="2019-08-18T00:02:42Z" level=info msg="Connected to postgres database: fathom.db"
time="2019-08-18T00:02:42Z" level=fatal msg="listen tcp :8080: bind: address already in use"
```

Am I doing something wrong here?
